version: '3'
services:
  portainer:
    image: portainer/portainer:arm
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "constraint:node==homecluster"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
